language: cpp

sudo: required
dist: trusty

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-8.0 && CXX=clang++-8.0"
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - ${CC} -v
    
before_script:
    - mkdir build
    - cd build
    - cmake ..
    
script: make
