language: cpp

sudo: required
dist: trusty

matrix:
  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-xenial-8
#          packages:
#            - clang-8
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - g++-8
      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - ${CC} -v
    
before_script:
    - mkdir build
    - cd build
    - cmake ..
    
script: make
