language: cpp

sudo: required
dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - g++-8
      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9 CODE_COVERAGE=ON"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 CODE_COVERAGE=OFF"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - ${CC} -v
    
before_script:
    - mkdir build
    - cd build
    - cmake .. -DENABLE_LLVM_COV=${CODE_COVERAGE} -DCMAKE_BUILD_TYPE=Debug
    
script: make

after_success:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ ${CODE_COVERAGE} == "ON" ]]; then
      ./Bin/UnitTest
      llvm-profdata merge -sparse default.profraw -o coverage.profdata
      llvm-cov show ./Bin/UnitTest -instr-profile=coverage.profdata > coverage.txt;
    fi
  - bash <(curl -s https://codecov.io/bash)