#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}


# branches to build
branches:
  only:
    - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

install:
  - choco install opencppcoverage
  - set path=C:\Program Files\OpenCppCoverage;%path%

# clone directory
clone_folder: C:\projects\Mathter

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several platforms to build matrix:
platform:
  - x64

# to add several configurations to build matrix:
configuration:
  - Debug
  - Release

build:
  parallel: true
  project: C:\projects\Mathter\build\Mathter.sln
  verbosity: normal


# scripts to run before build
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017 Win64"


#---------------------------------#
#             testing             #
#---------------------------------#

# run tests
test_script:
  - ps : |-
      mkdir test_results
      cd test_results
      iex "C:\projects\Mathter\build\Bin\$env:CONFIGURATION\Mathter.exe --reporter junit --out test.xml"
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test.xml))


