name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create tagged release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package project
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            For changes, check the commit log.
          draft: false
          prerelease: false
      - name: Install conan
        shell: bash
        run: |
          pip install --user conan
      - name: Deploy to conan
        working-directory: ${{runner.workspace}}
        shell: bash
        env:
          PACKAGE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          ~/.local/bin/conan remote add petiaccja_public https://api.bintray.com/conan/petiaccja/public-conan
          ~/.local/bin/conan user -p ${{ secrets.CONAN_BINTRAY_API_KEY }} -r petiaccja_public petiaccja
          ~/.local/bin/conan create $GITHUB_WORKSPACE mathter/${PACKAGE_VERSION:1}@
          ~/.local/bin/conan upload mathter/${PACKAGE_VERSION:1} --all --confirm -r petiaccja_public